#!/usr/bin/env python3
"""Regenerate BoilerCompass web and app assets from the supplied logo artwork."""

import base64
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "public/brand/boilercompass-logo-source.jpg"
MARK = ROOT / "public/brand/boilercompass-mark.png"
BACKGROUND = (246, 242, 232, 255)


def transparent_mark() -> Image.Image:
    """Remove only the exterior white field, preserving the enclosed dial."""
    image = Image.open(SOURCE).convert("RGBA")
    ImageDraw.floodfill(image, (0, 0), (255, 255, 255, 0), thresh=38)
    bbox = image.getchannel("A").getbbox()
    if bbox is None:
        raise SystemExit("The supplied logo has no visible artwork.")

    cropped = image.crop(bbox)
    side = max(cropped.size)
    padding = max(24, round(side * 0.045))
    canvas = Image.new("RGBA", (side + padding * 2, side + padding * 2))
    x = (canvas.width - cropped.width) // 2
    y = (canvas.height - cropped.height) // 2
    canvas.alpha_composite(cropped, (x, y))
    return canvas.resize((1024, 1024), Image.Resampling.LANCZOS)


def icon(mark: Image.Image, size: int, inset_ratio: float) -> Image.Image:
    canvas = Image.new("RGBA", (size, size), BACKGROUND)
    inset = round(size * inset_ratio)
    artwork = mark.resize(
        (size - inset * 2, size - inset * 2), Image.Resampling.LANCZOS
    )
    canvas.alpha_composite(artwork, (inset, inset))
    return canvas


if not SOURCE.exists():
    raise SystemExit(f"Missing supplied logo source: {SOURCE}")

mark = transparent_mark()
MARK.parent.mkdir(parents=True, exist_ok=True)
mark.save(MARK, format="PNG", optimize=True)

og_buffer = BytesIO()
mark.resize((256, 256), Image.Resampling.LANCZOS).save(
    og_buffer, format="PNG", optimize=True
)
og_data = base64.b64encode(og_buffer.getvalue()).decode("ascii")
(ROOT / "src/lib/brand-mark-data.ts").write_text(
    "// Generated by scripts/generate-brand-assets.py. Do not edit.\n"
    f'export const BOILERCOMPASS_MARK_DATA_URI = "data:image/png;base64,{og_data}";\n',
    encoding="utf-8",
)

outputs = {
    ROOT / "src/app/apple-icon.png": icon(mark, 180, 0.08),
    ROOT / "src/app/icon.png": icon(mark, 512, 0.07),
    ROOT / "public/brand/boilercompass-icon-192.png": icon(mark, 192, 0.08),
    ROOT / "public/brand/boilercompass-icon-512.png": icon(mark, 512, 0.2),
}
for output, image in outputs.items():
    output.parent.mkdir(parents=True, exist_ok=True)
    image.convert("RGB").save(output, format="PNG", optimize=True)

favicon = icon(mark, 256, 0.08).convert("RGBA")
favicon.save(
    ROOT / "src/app/favicon.ico",
    format="ICO",
    sizes=[(16, 16), (24, 24), (32, 32), (48, 48)],
)

print(
    "Generated transparent mark, Open Graph data URI, favicon.ico, "
    "apple-icon.png, icon.png, and 192/512px app icons."
)
